"use client"
import Image from 'next/image'
import type { Metadata } from 'next'
import PortfolioContent from '@/components/sections/portfolio/PortfolioContent'
import { useRouter } from 'next/navigation';
import { useEffect, useState } from 'react';
import useAxios from 'axios-hooks';
import { ArrowRightIcon } from '@heroicons/react/24/outline';
import Markdown from 'react-markdown'
import rehypeHighlight from 'rehype-highlight'
import { Progress } from '@/components/Progress';
import { useLocale, useTranslations } from 'next-intl';
import NavBar from '@/components/NavBar';
import Footer from '@/components/Footer';

// import {useRouter} from '@/navigation';

const metadata: Metadata = {
    title: 'Portfolio',
    description: 'Generated by create next app',
}

export default function Page({ params: { id } }: { params: { id: string } }) {
    const t = useTranslations("Portfolio");
    //@ts-ignore
    const lang: "ar" | "en" = useLocale();
    const [{ data: profilioData, loading, error }] = useAxios({
        url: `https://api.arabeelearning.com/api/yhh-profilios/${id}?populate=cover&locale=${lang}`,
        method: "GET",
        headers: {
            Authorization: `Bearer ${process.env.NEXT_PUBLIC_API_KEY}`
        }
    })
    const [profilio, setProfilio] = useState<any>(null)

    useEffect(() => {
        if (profilioData && "data" in profilioData && profilioData?.data !== null) {
            setProfilio(profilioData?.data)
        }
    }, [profilioData])

    if (loading) {
        return (
            <main className="w-full">
                <div className='px-5 md:px-10'>
                    <div className="w-full max-w-7xl mx-auto">
                        <div className="mt-[-14px] mb-[-18px] pt-16 pb-[6.9rem] sm:my-0 sm:py-32 flex justify-center">
                            <Progress />
                        </div>
                    </div>
                </div>
            </main>
        )
    }

    if (!profilio) {
        return (
            <main className="w-full">
                <div className='px-5 md:px-10'>
                    <div className="w-full max-w-7xl mx-auto">
                        <div className="mt-[-14px] mb-[-18px] pt-16 pb-[6.9rem] sm:my-0 sm:py-32 flex justify-center">
                            <h1 className="text-xl text-[#f25260] font-extrabold md:text-3xl lg:text-5xl">404</h1>
                        </div>
                    </div>
                </div>
            </main>
        )
    }

    return (
        <>
            <NavBar />
            <main className="w-full">
                <div className='px-5 md:px-10'>
                    <div className="w-full max-w-7xl mx-auto">
                        <div className="mt-[-14px] mb-[-18px] pt-16 pb-[6.9rem] sm:my-0 sm:py-32">
                            <div className="max-w-[48rem] flex items-start flex-col ps-[16px] md:ps-0">
                                <div className="flex items-start gap-2 mb-[12px]">
                                    <div className='circle-icon bg-[#f25260]'></div>
                                    <div className='triangule-icon2 border-transparent border-t-[#47bdff] border-s-[#47bdff]'></div>
                                </div>
                                <h2 className="text-2xl sm:text-[2.5rem] md:text-5xl leading-[1.2] font-bold text-[#28264d] mb-[10px]">{profilio?.attributes?.category}</h2>

                                <p className="mt-5 mb-0 md:mb-auto md:mt-8 text-[.8rem] md:text-[1.1rem] leading-6 text-[#28264d] opacity-65 px-[16px] md:px-0 ml-[-0.9rem] md:ml-0">{profilio?.attributes?.short_description}</p>
                            </div>

                            <div className="max-w-[60rem] mt-12 grid gap-4 grid-cols-1 md:gap-4 md:grid-cols-4 relative">
                                <div>
                                    <div className="mb-4 text-base text-[#69778c]">{t("service")}</div>
                                    <div className="text-[1.1rem] text-[#28264d]">{profilio?.attributes?.service}</div>
                                </div>
                                <div>
                                    <div className="mb-4 text-base text-[#69778c]">{t("deliverables")}</div>
                                    <div className="text-[1.1rem] text-[#28264d]">{profilio?.attributes?.deliverables}</div>
                                </div>
                                {profilio?.attributes?.website && profilio?.attributes?.website !== ""
                                    ? <div>
                                        <div className="mb-4 text-base text-[#69778c]">{t("website")}</div>
                                        <a href={profilio?.attributes?.website} target='_blank' className="flex items-center gap-2 text-[1.1rem] text-[#28264d] duration-700 hover:gap-4">
                                            {t("link")}
                                            <ArrowRightIcon className="w-4" aria-hidden="true" />
                                        </a>
                                    </div>
                                    : null
                                }
                            </div>

                            <div className="mt-16">
                                <img height="400" loading="eager" width="400" src={profilio?.attributes?.cover?.data?.attributes?.url} alt={profilio?.attributes?.cover?.data?.attributes?.alternativeText} sizes="(max-width: 479px) 92vw, (max-width: 767px) 95vw, (max-width: 991px) 92vw, (max-width: 1439px) 94vw, 1280px" className="cover-image"></img>
                            </div>
                        </div>
                        <div className="h-[1px] bg-[#e4e8ed]"></div>
                    </div>
                </div>

                <div className='px-5 md:px-10'>
                    <div className="w-full max-w-7xl mx-auto">
                        <div className="mt-[-14px] mb-[-18px] pt-16 pb-[6.9rem] sm:my-0 sm:py-32">
                            <div className="max-w-[48rem] flex items-start flex-col ps-[16px] md:ps-0">
                                <h2 className="text-xl sm:text-4xl leading-[1.2] font-bold text-[#28264d] mb-[60px]">{t("overview")}</h2>
                                <Markdown 
                                rehypePlugins={[rehypeHighlight]}
                                className="markdown-container"
                                >
                                    {profilio?.attributes?.overview}
                                </Markdown>
                                {/* <p className="mt-5 mb-0 md:mb-auto md:mt-8 text-[.8rem] md:text-base leading-6 text-[#28264d] opacity-65 px-[16px] md:px-0 ml-[-0.9rem] md:ml-0">{profilio?.attributes?.overview}</p> */}

                            </div>
                        </div>
                        <div className="h-[1px] bg-[#e4e8ed]"></div>
                    </div>
                </div>
            </main>
            <Footer />
        </>
    )
}
