version: "3"
services:
  yhh-website:
    container_name: yhh-website
    image: registry.da2ova.com/yhh-website:latest
    restart: always
    networks:
      - web_default

networks:
  web_default:
    driver: bridge
    external: true