"use client"
import type { Metadata } from 'next'
import { useEffect, useState } from 'react';
import useAxios from 'axios-hooks';
import { ArrowRightIcon } from '@heroicons/react/24/outline';
import Markdown from 'react-markdown'
import rehypeHighlight from 'rehype-highlight'
import { Progress } from '@/components/Progress';
import { useLocale } from 'next-intl';
import NavBar from '@/components/NavBar';
import Footer from '@/components/Footer';

// import {useRouter} from '@/navigation';

const metadata: Metadata = {
    title: 'Portfolio',
    description: 'Generated by create next app',
}

export default function Page({ params: { id } }: { params: { id: string } }) {
    //@ts-ignore
    const lang: "ar" | "en" = useLocale();
    const [{ data: blogData, loading, error }] = useAxios({
        url: `https://api.arabeelearning.com/api/yhh-blogs/${id}?populate=cover_image&locale=${lang}`,
        method: "GET",
        headers: {
            Authorization: `Bearer ${process.env.NEXT_PUBLIC_API_KEY}`
        }
    })
    const [blog, setBlog] = useState<any>(null)

    useEffect(() => {
        if (blogData && "data" in blogData && blogData?.data !== null) {
            setBlog(blogData?.data)
        }
    }, [blogData])

    if (loading) {
        return (
            <main className="w-full">
                <div className='px-5 md:px-10'>
                    <div className="w-full max-w-7xl mx-auto">
                        <div className="mt-[-14px] mb-[-18px] pt-16 pb-[6.9rem] sm:my-0 sm:py-32 flex justify-center">
                            <Progress />
                        </div>
                    </div>
                </div>
            </main>
        )
    }

    if (!blog) {
        return (
            <main className="w-full">
                <div className='px-5 md:px-10'>
                    <div className="w-full max-w-7xl mx-auto">
                        <div className="mt-[-14px] mb-[-18px] pt-16 pb-[6.9rem] sm:my-0 sm:py-32 flex justify-center">
                            <h1 className="text-xl text-[#f25260] font-extrabold md:text-3xl lg:text-5xl">404</h1>
                        </div>
                    </div>
                </div>
            </main>
        )
    }

    return (
        <>
            <NavBar />
            <main className="w-full">
                <div className='px-5 md:px-10'>
                    <div className="w-full max-w-7xl mx-auto">
                        <div className="mt-[-14px] mb-[-18px] pt-16 pb-[6.9rem] sm:my-0 sm:py-32">
                            <div className="max-w-[48rem] flex items-start flex-col ps-[16px] md:ps-0">
                                <div className="flex items-start gap-2 mb-[12px]">
                                    <div className='circle-icon bg-[#f25260]'></div>
                                    <div className='triangule-icon2 border-transparent border-t-[#47bdff] border-s-[#47bdff]'></div>
                                </div>
                                <h2 className="text-2xl sm:text-[2.5rem] md:text-5xl leading-[1.2] font-bold text-[#28264d] mb-[10px]">{blog?.attributes?.title}</h2>
                            </div>

                            <div className="mt-16">
                                <img height="400" loading="eager" width="400" src={blog?.attributes?.cover_image?.data?.attributes?.url} alt={blog?.attributes?.cover_image?.data?.attributes?.alternativeText} sizes="(max-width: 479px) 92vw, (max-width: 767px) 95vw, (max-width: 991px) 92vw, (max-width: 1439px) 94vw, 1280px" className="cover-image"></img>
                            </div>
                        </div>
                        <div className="h-[1px] bg-[#e4e8ed]"></div>
                    </div>
                </div>

                <div className='px-5 md:px-10'>
                    <div className="w-full max-w-7xl mx-auto">
                        <div className="mt-[-14px] mb-[-18px] pt-16 pb-[6.9rem] sm:my-0 sm:py-32">
                            <div className="max-w-[48rem] flex items-start flex-col ps-[16px] md:ps-0">
                                <Markdown rehypePlugins={[rehypeHighlight]}>
                                    {blog?.attributes?.body}
                                </Markdown>
                            </div>
                        </div>
                        <div className="h-[1px] bg-[#e4e8ed]"></div>
                    </div>
                </div>
            </main>
            <Footer />
        </>
    )
}
